disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - missing_docs
  - unneeded_override
  - cyclomatic_complexity
  - nesting
opt_in_rules:
  - empty_count
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - multiline_function_chains
analyzer_rules:
  - unused_import
  - capture_variable
  - unused_declaration
included:
  - Projects
excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
force_cast: warning
force_try:
  severity: warning
line_length: 200
function_body_length:
  warning: 150
  error: 200
type_body_length:
  - 400
  - 500
file_length:
  warning: 600
  error: 1000
type_name:
  min_length: 4
  max_length:
    warning: 50
    error: 60
  excluded: iPhone
  allowed_symbols: "_"
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - x
    - y
    - id
    - uid
    - URL
    - GlobalAPIKey
    - ^[A-Z][a-zA-Z0-9]*$
  allowed_symbols: "_"
reporter: "xcode"
