//
//  CreateAnnouncementUsecase.swift
//  AnnouncementUsecase
//
//  Created by DOYEON LEE on 8/19/24.
//

import AnnouncementDataInterface
import AnnouncementEntity
import Container
import Foundation
import RxSwift
import Swinject
import UserDefaultsUtility

public struct CreateAnnouncementUsecase {
    // MARK: DTO

    public struct Input {
        let newAnnouncement: AnnouncementEntity
        
        public init(
            newAnnouncement: AnnouncementEntity
        ) {
            self.newAnnouncement = newAnnouncement
        }
    }
    
    public struct Output {
        public let announcementId: Int
    }
    
    // MARK: Dependency

    let announcementRepository = Container.shared
        .resolve(AnnouncementRepositoryInterface.self)!
    
    let memberUserDefaultsManager = UserDefaultsManager<Member>()
    
    // MARK: Initializer

    public init() {}
    
    // MARK: Execute method

    public func execute(_ input: Input) -> Observable<Output> {
        var newAnnouncement = input.newAnnouncement
        
        // endAt이 nil이면 한 달 뒤의 날짜로 설정
        let autoGeneratedEndAt = Calendar.current
            .date(byAdding: .month, value: 1, to: Date())!
        
        print("::: autoGeneratedEndAt \(autoGeneratedEndAt)")
        
        if let member = memberUserDefaultsManager.get() {
            return announcementRepository
                .createAnnouncement(
                    .init(
                        organizationId: newAnnouncement.organizationId,
                        memberId: member.id,
                        title: newAnnouncement.title,
                        content: newAnnouncement.body,
                        endAt: newAnnouncement.endAt ?? autoGeneratedEndAt,
                        noticeBefore: [],
                        noticeDate: []
                    )
                )
                .map { result in
                    Output(announcementId: Int(result.announcementId ?? 0)) // TODO: optional 처리
                }
        } else {
            fatalError("해당 유즈케이스는 로그인 상태에서 실행되어야합니다.")
        }
    }
}
