# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload the main Notitime app to TestFlight"
  lane :beta_noffice_app do
    app_identifier = "notitime.noffice.app"
    
    match(
      type: "appstore",
      app_identifier: app_identifier,
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    last_testflight_build_number = latest_testflight_build_number(
      app_identifier: "notitime.noffice.app",
      version: ENV["APP_VERSION"] # 현재 버전 입력
    )
    
    increment_build_number(
      xcodeproj: "./Projects/Noffice/Noffice.xcodeproj",
      build_number: (last_testflight_build_number.to_i + 1).to_s
    )
    
    build_app(
      scheme: "Noffice",
      workspace: "./Noffice-Workspace.xcworkspace",
      configuration: "prod",
      clean: true,
      export_method: "app-store"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  lane :beta_designsystem_app do
    app_identifier = "notitime.noffice.design-system.app"
    
    match(
      type: "appstore",
      app_identifier: app_identifier,
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    last_testflight_build_number = latest_testflight_build_number(
      app_identifier: "notitime.noffice.design-system.app",
      version: ENV["APP_VERSION"] # 현재 버전 입력
    )
    
    increment_build_number(
      xcodeproj: "./Projects/UI/DesignSystemUIModule/DesignSystemModule.xcodeproj",
      build_number: (last_testflight_build_number.to_i + 1).to_s
    )
    
    build_app(
      scheme: "DesignSystem",
      workspace: "./Noffice-Workspace.xcworkspace",
      configuration: "prod",
      clean: true,
      export_method: "app-store"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Fetch development certificates and profiles, and build the app for development"
  lane :development do
    sync_code_signing(type: "development")
    build_app(scheme: "dev")
  end

  desc "Fetch app store certificates and profiles, and build the app for distribution"
  lane :appstore do
    sync_code_signing(type: "appstore")
    build_app(scheme: "prod")
  end
end
